//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulZil.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Lessons : global::System.Configuration.ApplicationSettingsBase {
        
        private static Lessons defaultInstance = ((Lessons)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Lessons())));
        
        public static Lessons Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_1_student {
            get {
                return ((global::System.TimeSpan)(this["monday_1_student"]));
            }
            set {
                this["monday_1_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_2_student {
            get {
                return ((global::System.TimeSpan)(this["monday_2_student"]));
            }
            set {
                this["monday_2_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_3_student {
            get {
                return ((global::System.TimeSpan)(this["monday_3_student"]));
            }
            set {
                this["monday_3_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_4_student {
            get {
                return ((global::System.TimeSpan)(this["monday_4_student"]));
            }
            set {
                this["monday_4_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_5_student {
            get {
                return ((global::System.TimeSpan)(this["monday_5_student"]));
            }
            set {
                this["monday_5_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_6_student {
            get {
                return ((global::System.TimeSpan)(this["monday_6_student"]));
            }
            set {
                this["monday_6_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_7_student {
            get {
                return ((global::System.TimeSpan)(this["monday_7_student"]));
            }
            set {
                this["monday_7_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_8_student {
            get {
                return ((global::System.TimeSpan)(this["monday_8_student"]));
            }
            set {
                this["monday_8_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_9_student {
            get {
                return ((global::System.TimeSpan)(this["monday_9_student"]));
            }
            set {
                this["monday_9_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_10_student {
            get {
                return ((global::System.TimeSpan)(this["monday_10_student"]));
            }
            set {
                this["monday_10_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_11_student {
            get {
                return ((global::System.TimeSpan)(this["monday_11_student"]));
            }
            set {
                this["monday_11_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_12_student {
            get {
                return ((global::System.TimeSpan)(this["monday_12_student"]));
            }
            set {
                this["monday_12_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_13_student {
            get {
                return ((global::System.TimeSpan)(this["monday_13_student"]));
            }
            set {
                this["monday_13_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_14_student {
            get {
                return ((global::System.TimeSpan)(this["monday_14_student"]));
            }
            set {
                this["monday_14_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_15_student {
            get {
                return ((global::System.TimeSpan)(this["monday_15_student"]));
            }
            set {
                this["monday_15_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_16_student {
            get {
                return ((global::System.TimeSpan)(this["monday_16_student"]));
            }
            set {
                this["monday_16_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_17_student {
            get {
                return ((global::System.TimeSpan)(this["monday_17_student"]));
            }
            set {
                this["monday_17_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_18_student {
            get {
                return ((global::System.TimeSpan)(this["monday_18_student"]));
            }
            set {
                this["monday_18_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_19_student {
            get {
                return ((global::System.TimeSpan)(this["monday_19_student"]));
            }
            set {
                this["monday_19_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_20_student {
            get {
                return ((global::System.TimeSpan)(this["monday_20_student"]));
            }
            set {
                this["monday_20_student"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_1_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_1_teacher"]));
            }
            set {
                this["monday_1_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_2_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_2_teacher"]));
            }
            set {
                this["monday_2_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_3_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_3_teacher"]));
            }
            set {
                this["monday_3_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_4_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_4_teacher"]));
            }
            set {
                this["monday_4_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_5_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_5_teacher"]));
            }
            set {
                this["monday_5_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_6_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_6_teacher"]));
            }
            set {
                this["monday_6_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_7_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_7_teacher"]));
            }
            set {
                this["monday_7_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_8_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_8_teacher"]));
            }
            set {
                this["monday_8_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_9_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_9_teacher"]));
            }
            set {
                this["monday_9_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_10_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_10_teacher"]));
            }
            set {
                this["monday_10_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_11_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_11_teacher"]));
            }
            set {
                this["monday_11_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_12_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_12_teacher"]));
            }
            set {
                this["monday_12_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_13_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_13_teacher"]));
            }
            set {
                this["monday_13_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_14_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_14_teacher"]));
            }
            set {
                this["monday_14_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_15_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_15_teacher"]));
            }
            set {
                this["monday_15_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_16_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_16_teacher"]));
            }
            set {
                this["monday_16_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_17_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_17_teacher"]));
            }
            set {
                this["monday_17_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_18_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_18_teacher"]));
            }
            set {
                this["monday_18_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_19_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_19_teacher"]));
            }
            set {
                this["monday_19_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_20_teacher {
            get {
                return ((global::System.TimeSpan)(this["monday_20_teacher"]));
            }
            set {
                this["monday_20_teacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_1_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_1_exit"]));
            }
            set {
                this["monday_1_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_2_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_2_exit"]));
            }
            set {
                this["monday_2_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_3_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_3_exit"]));
            }
            set {
                this["monday_3_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_4_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_4_exit"]));
            }
            set {
                this["monday_4_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_5_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_5_exit"]));
            }
            set {
                this["monday_5_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_6_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_6_exit"]));
            }
            set {
                this["monday_6_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_7_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_7_exit"]));
            }
            set {
                this["monday_7_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_8_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_8_exit"]));
            }
            set {
                this["monday_8_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_9_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_9_exit"]));
            }
            set {
                this["monday_9_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_10_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_10_exit"]));
            }
            set {
                this["monday_10_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_11_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_11_exit"]));
            }
            set {
                this["monday_11_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_12_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_12_exit"]));
            }
            set {
                this["monday_12_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_13_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_13_exit"]));
            }
            set {
                this["monday_13_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_14_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_14_exit"]));
            }
            set {
                this["monday_14_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_15_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_15_exit"]));
            }
            set {
                this["monday_15_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_16_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_16_exit"]));
            }
            set {
                this["monday_16_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_17_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_17_exit"]));
            }
            set {
                this["monday_17_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_18_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_18_exit"]));
            }
            set {
                this["monday_18_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_19_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_19_exit"]));
            }
            set {
                this["monday_19_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan monday_20_exit {
            get {
                return ((global::System.TimeSpan)(this["monday_20_exit"]));
            }
            set {
                this["monday_20_exit"] = value;
            }
        }
    }
}
